[package]
name = "ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
path = "src/ui.rs"

[dependencies]
gpui.workspace = true
theme.workspace = true
unicode-segmentation = "1"

[target.'cfg(target_os = "windows")'.dependencies]
raw-window-handle = "0.6"
windows = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_UI_Input_KeyboardAndMouse",
] }
